# Generated by Django 5.1.1 on 2024-09-15 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('genre', models.CharField(choices=[('fitness', 'Fitness'), ('chess', 'Chess'), ('pets', 'Pets'), ('holiday', 'Holiday')], default='fitness', max_length=20)),
            ],
        ),
    ]
